# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThatDubaiGirl' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThatDubaiGirl
  pod 'IQKeyboardManagerSwift'
  pod 'JGProgressHUD'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'HMSegmentedControl'
  pod 'Cosmos', '~> 23.0'
  # pod 'Stripe'

end
